target("quickjs")
    set_kind("shared")
    add_files("quickjs*.c", "cutils.c", "lib*.c")
    add_headerfiles("quickjs-libc.h")
    add_headerfiles("quickjs.h")
    add_installfiles("*.js", {prefixdir = "share"})
    set_languages("c99")
    -- add_defines("CONFIG_VERSION=\"2024-02-14\"", "EMSCRIPTEN", "CONFIG_BIGNUM", "_GNU_SOURCE", "__USE_MINGW_ANSI_STDIO")
    add_defines("CONFIG_VERSION=\"2024-02-14\"", "CONFIG_BIGNUM", "_GNU_SOURCE", "__USE_MINGW_ANSI_STDIO")
    set_toolchains("mingw")
    set_arch("x64")
    -- set_arch("x86")
    add_syslinks("pthread")